import React, { useRef, useState } from 'react';
import { X, Download, Image, FileText, Copy, Check } from 'lucide-react';
import './ExportCard.css';

export default function ExportCard({ project, globalStore, totalSelected, stores, onClose }) {
  const cardRef = useRef(null);
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);
  const [selectedExportStore, setSelectedExportStore] = useState(globalStore || '');

  const allStores = [...new Set(
    (project.components || []).flatMap(c => (c.prices || []).map(p => p.store))
  )].sort();

  function getComponentPrice(comp, store) {
    if (!comp.prices || comp.prices.length === 0) return null;
    const storeKey = store || comp.selectedStore;
    const match = storeKey ? comp.prices.find(p => p.store === storeKey) : null;
    if (match) return match.price;
    return Math.min(...comp.prices.map(p => p.price));
  }

  function getTotal(store) {
    let total = 0;
    for (const comp of (project.components || [])) {
      const price = getComponentPrice(comp, store);
      if (price != null) total += price * (comp.quantity || 1);
    }
    return total;
  }

  const exportTotal = getTotal(selectedExportStore);

  // Group by category
  const grouped = {};
  const uncategorized = [];
  for (const comp of (project.components || [])) {
    if (comp.category) {
      if (!grouped[comp.category]) grouped[comp.category] = [];
      grouped[comp.category].push(comp);
    } else {
      uncategorized.push(comp);
    }
  }
  const groups = [
    ...Object.entries(grouped).map(([cat, comps]) => ({ cat, comps })),
    ...(uncategorized.length > 0 ? [{ cat: 'Other', comps: uncategorized }] : [])
  ];

  async function downloadAsImage() {
    setExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: '#0a0a0f',
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const link = document.createElement('a');
      link.download = `${project.name.replace(/\s+/g, '_')}_checklist.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error('Export failed:', err);
      alert('Image export failed. Try the text copy option instead.');
    }
    setExporting(false);
  }

  function copyAsText() {
    const lines = [
      `═══════════════════════════════════`,
      `  TAKA TRACKER — PURCHASE CHECKLIST`,
      `═══════════════════════════════════`,
      `Project: ${project.name}`,
      project.description ? `Note: ${project.description}` : '',
      selectedExportStore ? `Store: ${selectedExportStore}` : `Store: Best available price`,
      `Date: ${new Date().toLocaleDateString('en-BD', { day:'numeric', month:'long', year:'numeric' })}`,
      `───────────────────────────────────`,
      '',
    ];

    for (const { cat, comps } of groups) {
      lines.push(`[ ${cat.toUpperCase()} ]`);
      for (const comp of comps) {
        const price = getComponentPrice(comp, selectedExportStore);
        const total = price != null ? price * (comp.quantity || 1) : null;
        const storeStr = selectedExportStore || comp.selectedStore || 'best';
        lines.push(`  ☐  ${comp.name}`);
        lines.push(`     Qty: ${comp.quantity || 1}  |  Price: ${price != null ? '৳' + price.toLocaleString() : 'N/A'}  |  Total: ${total != null ? '৳' + total.toLocaleString() : 'N/A'}  |  Store: ${storeStr}`);
        if (comp.notes) lines.push(`     Notes: ${comp.notes}`);
      }
      lines.push('');
    }

    lines.push(`───────────────────────────────────`);
    lines.push(`GRAND TOTAL: ৳${exportTotal.toLocaleString('en-BD')}`);
    lines.push(`Components: ${project.components.length}`);
    lines.push(`Generated by TakaTracker`);

    const text = lines.filter(l => l !== null).join('\n');
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  return (
    <div className="ec-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="ec-modal fade-in">
        <div className="ec-modal-header">
          <h2 className="ec-modal-title">Export Checklist</h2>
          <button className="ec-close-btn" onClick={onClose}><X size={18} /></button>
        </div>

        {/* Store selector for export */}
        <div className="ec-store-select-row">
          <label className="ec-store-label mono">EVALUATE FROM STORE</label>
          <select
            value={selectedExportStore}
            onChange={e => setSelectedExportStore(e.target.value)}
            className="ec-store-sel"
          >
            <option value="">Best available price</option>
            {[...stores, ...allStores.filter(s => !stores.includes(s))].map(s =>
              <option key={s} value={s}>{s}</option>
            )}
          </select>
        </div>

        {/* Preview card */}
        <div className="ec-preview-scroll">
          <div ref={cardRef} className="ec-card">
            {/* Card header */}
            <div className="ec-card-header">
              <div className="ec-card-logo">
                <span className="ec-logo-icon">৳</span>
                <span className="ec-logo-text">Taka<strong>Tracker</strong></span>
              </div>
              <div className="ec-card-meta-right">
                <div className="ec-card-date">{new Date().toLocaleDateString('en-BD', { day:'numeric', month:'short', year:'numeric' })}</div>
                {selectedExportStore && <div className="ec-card-store-tag">{selectedExportStore}</div>}
              </div>
            </div>

            <div className="ec-card-project-name">{project.name}</div>
            {project.description && <div className="ec-card-project-desc">{project.description}</div>}

            <div className="ec-card-divider" />

            {/* Component groups */}
            {groups.map(({ cat, comps }) => (
              <div key={cat} className="ec-card-group">
                <div className="ec-card-cat-label">{cat}</div>
                {comps.map((comp, i) => {
                  const price = getComponentPrice(comp, selectedExportStore);
                  const lineTotal = price != null ? price * (comp.quantity || 1) : null;
                  const storeUsed = selectedExportStore || comp.selectedStore;
                  const actualStore = storeUsed && comp.prices?.find(p => p.store === storeUsed)
                    ? storeUsed
                    : (comp.prices?.length > 0 ? comp.prices.find(p => p.price === Math.min(...comp.prices.map(x => x.price)))?.store : null);

                  return (
                    <div key={comp.id} className={`ec-card-row ${i % 2 === 0 ? 'ec-row-alt' : ''}`}>
                      <div className="ec-card-check" />
                      <div className="ec-card-comp-info">
                        <div className="ec-card-comp-name">{comp.name}</div>
                        {actualStore && <div className="ec-card-comp-store">{actualStore}</div>}
                        {comp.notes && <div className="ec-card-comp-notes">{comp.notes}</div>}
                      </div>
                      <div className="ec-card-comp-right">
                        <div className="ec-card-comp-qty">×{comp.quantity || 1}</div>
                        {price != null ? (
                          <div className="ec-card-comp-price">৳{price.toLocaleString()}</div>
                        ) : (
                          <div className="ec-card-comp-no-price">N/A</div>
                        )}
                        {lineTotal != null && (comp.quantity || 1) > 1 && (
                          <div className="ec-card-comp-total">৳{lineTotal.toLocaleString()}</div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            ))}

            <div className="ec-card-divider" />

            {/* Summary */}
            <div className="ec-card-summary">
              <div className="ec-card-summary-row">
                <span>Total Components</span>
                <span className="mono">{project.components.length}</span>
              </div>
              <div className="ec-card-summary-row ec-grand-total">
                <span>Grand Total</span>
                <span className="mono ec-total-num">৳{exportTotal.toLocaleString('en-BD')}</span>
              </div>
            </div>

            <div className="ec-card-footer">
              Generated with TakaTracker • Made for BD Makers
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="ec-actions">
          <button className="btn-primary" onClick={downloadAsImage} disabled={exporting}>
            {exporting ? (
              <><span className="pulse">⟳</span> Generating...</>
            ) : (
              <><Image size={15} /> Download PNG</>
            )}
          </button>
          <button className="btn-ghost" onClick={copyAsText}>
            {copied ? <><Check size={15} /> Copied!</> : <><Copy size={15} /> Copy as Text</>}
          </button>
        </div>
      </div>
    </div>
  );
}
